sonar.projectKey=gopisuvarna_skill_gap_analyzer
sonar.organization=gopisuvarna

sonar.sources=backend,frontend
sonar.tests=backend/tests,frontend/tests

sonar.test.inclusions=backend/tests/**/*.py,backend/**/tests.py,frontend/tests/**/*.spec.ts,frontend/tests/**/*.spec.tsx,frontend/tests/**/*.test.ts,frontend/tests/**/*.test.tsx

sonar.exclusions=backend/**/migrations/**,backend/staticfiles/**,backend/env/**,backend/venv/**,backend/media/**,frontend/.next/**,frontend/coverage/**,frontend/test-results/**,node_modules/**

sonar.coverage.exclusions=frontend/eslint.config.js,frontend/next.config.js,frontend/postcss.config.js,frontend/playwright.config.ts,frontend/app/layout.tsx,frontend/app/page.tsx,frontend/app/login/**,frontend/app/register/**,backend/manage.py,backend/tests/**,backend/config/asgi.py,backend/config/wsgi.py,backend/config/settings.py,backend/config/test_settings.py,backend/config/urls.py

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
