"""
Skill name normalization.

Maps raw/variant skill strings (e.g. "js", "node.js", "reactjs")
to canonical display names (e.g. "JavaScript", "Node.js", "React").
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Canonical skill name constants
# ---------------------------------------------------------------------------
_NEXT_JS           = "Next.js"
_VUE_JS            = "Vue.js"
_EXPRESS_JS        = "Express.js"
_NODE_JS           = "Node.js"
_RUBY_ON_RAILS     = "Ruby on Rails"
_MATERIAL_UI       = "Material UI"
_SHADCN            = "shadcn/ui"
_SQL_SERVER        = "SQL Server"
_CI_CD             = "CI/CD"
_ELK_STACK         = "ELK Stack"
_REST_API          = "REST API"
_MACHINE_LEARNING  = "Machine Learning"
_COMPUTER_VISION   = "Computer Vision"
_NEURAL_NETWORKS   = "Neural Networks"
_DATA_ANALYSIS     = "Data Analysis"
_DATA_VIZ          = "Data Visualization"
_JUPYTER           = "Jupyter Notebook"
_PEN_TESTING       = "Penetration Testing"
_SSL_TLS           = "SSL/TLS"
_REACT_NATIVE      = "React Native"
_VS_CODE           = "VS Code"
_BACKEND_DEV       = "Backend Development"
_FRONTEND_DEV      = "Frontend Development"
_DATA_STRUCTURES   = "Data Structures"

# ---------------------------------------------------------------------------
# Normalization map
# ---------------------------------------------------------------------------
_SKILL_NORMALIZATION_MAP = {
    # ── Programming Languages ──────────────────────────────────────
    "python": "Python",          "python3": "Python",           "python 3": "Python",
    "java": "Java",
    "javascript": "JavaScript",  "js": "JavaScript",
    "typescript": "TypeScript",  "ts": "TypeScript",
    "c++": "C++",                "cpp": "C++",                  "c plus plus": "C++",
    "c#": "C#",                  "csharp": "C#",                "c sharp": "C#",
    "c": "C",
    "go": "Go",                  "golang": "Go",
    "rust": "Rust",
    "php": "PHP",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "ruby": "Ruby",
    "scala": "Scala",
    "r": "R",
    "matlab": "MATLAB",
    "perl": "Perl",
    "shell": "Shell Scripting",  "shell scripting": "Shell Scripting",
    "bash": "Bash",              "bash scripting": "Bash",
    "powershell": "PowerShell",
    "groovy": "Groovy",
    "dart": "Dart",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "lua": "Lua",
    "assembly": "Assembly",
    "vba": "VBA",
    "cobol": "COBOL",
    "fortran": "Fortran",

    # ── Web Frameworks & Libraries ─────────────────────────────────
    "react": "React",            "react.js": "React",           "reactjs": "React",        "react js": "React",
    "next.js": _NEXT_JS,         "nextjs": _NEXT_JS,            "next js": _NEXT_JS,
    "vue": _VUE_JS,              "vue.js": _VUE_JS,             "vuejs": _VUE_JS,           "vue js": _VUE_JS,
    "angular": "Angular",        "angularjs": "AngularJS",      "angular.js": "AngularJS",
    "svelte": "Svelte",
    "ember": "Ember.js",         "ember.js": "Ember.js",
    "backbone": "Backbone.js",   "backbone.js": "Backbone.js",
    "jquery": "jQuery",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",        "fast api": "FastAPI",
    "express": _EXPRESS_JS,      "express.js": _EXPRESS_JS,     "expressjs": _EXPRESS_JS,
    "node": _NODE_JS,            "node.js": _NODE_JS,           "nodejs": _NODE_JS,         "node js": _NODE_JS,
    "spring": "Spring",          "spring boot": "Spring Boot",  "springboot": "Spring Boot",
    "laravel": "Laravel",
    "rails": _RUBY_ON_RAILS,     "ruby on rails": _RUBY_ON_RAILS, "ror": _RUBY_ON_RAILS,
    "asp.net": "ASP.NET",        "asp net": "ASP.NET",
    ".net": ".NET",              "dotnet": ".NET",              "dot net": ".NET",          ".net core": ".NET",  "dotnet core": ".NET",
    "blazor": "Blazor",
    "nest": "NestJS",            "nestjs": "NestJS",            "nest.js": "NestJS",
    "nuxt": "Nuxt.js",           "nuxt.js": "Nuxt.js",
    "gatsby": "Gatsby",
    "remix": "Remix",
    "htmx": "HTMX",
    "fastify": "Fastify",
    "koa": "Koa.js",
    "hapi": "Hapi.js",
    "strapi": "Strapi",

    # ── Frontend / UI ──────────────────────────────────────────────
    "html": "HTML",              "html5": "HTML",
    "css": "CSS",                "css3": "CSS",                 "less": "CSS",
    "sass": "SASS",              "scss": "SASS",
    "tailwind": "Tailwind",      "tailwind css": "Tailwind",    "tailwindcss": "Tailwind",
    "bootstrap": "Bootstrap",
    "material ui": _MATERIAL_UI, "materialui": _MATERIAL_UI,    "mui": _MATERIAL_UI,
    "chakra ui": "Chakra UI",
    "shadcn": _SHADCN,           "shadcn/ui": _SHADCN,
    "ant design": "Ant Design",  "antd": "Ant Design",
    "styled components": "Styled Components",
    "emotion": "CSS-in-JS",
    "webpack": "Webpack",
    "vite": "Vite",
    "rollup": "Rollup",
    "babel": "Babel",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "storybook": "Storybook",
    "figma": "Figma",
    "adobe xd": "Adobe XD",
    "sketch": "Sketch",
    "ui": "UI Design",           "ux": "UX Design",             "ui/ux": "UI/UX Design",    "ui ux": "UI/UX Design",
    "responsive design": "Responsive Design",
    "web design": "Web Design",
    "accessibility": "Accessibility", "wcag": "Accessibility",   "aria": "Accessibility",

    # ── Databases ──────────────────────────────────────────────────
    "postgresql": "PostgreSQL",  "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",          "sqlite3": "SQLite",
    "mongodb": "MongoDB",        "mongo": "MongoDB",            "mongo db": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch", "elastic search": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",      "dynamo db": "DynamoDB",
    "firestore": "Firestore",
    "firebase": "Firebase",
    "supabase": "Supabase",
    "neo4j": "Neo4j",
    "couchdb": "CouchDB",
    "mariadb": "MariaDB",
    "oracle": "Oracle DB",       "oracle db": "Oracle DB",
    "mssql": _SQL_SERVER,        "sql server": _SQL_SERVER,     "ms sql": _SQL_SERVER,      "microsoft sql server": _SQL_SERVER,
    "cockroachdb": "CockroachDB",
    "planetscale": "PlanetScale",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "sql": "SQL",
    "nosql": "NoSQL",            "no sql": "NoSQL",
    "database": "Databases",     "databases": "Databases",      "db": "Databases",
    "orm": "ORM",
    "prisma": "Prisma",
    "sequelize": "Sequelize",
    "mongoose": "Mongoose",
    "sqlalchemy": "SQLAlchemy",
    "hibernate": "Hibernate",

    # ── Cloud & DevOps ─────────────────────────────────────────────
    "aws": "AWS",                "amazon web services": "AWS",  "amazon aws": "AWS",
    "azure": "Azure",            "microsoft azure": "Azure",
    "gcp": "GCP",                "google cloud": "GCP",         "google cloud platform": "GCP",
    "digitalocean": "DigitalOcean",
    "heroku": "Heroku",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "cloudflare": "Cloudflare",
    "docker": "Docker",
    "kubernetes": "Kubernetes",  "k8s": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "puppet": "Puppet",
    "chef": "Chef",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",    "gitlab ci/cd": "GitLab CI",
    "circle ci": "CircleCI",     "circleci": "CircleCI",
    "travis ci": "Travis CI",    "travisci": "Travis CI",
    "ci/cd": _CI_CD,             "ci cd": _CI_CD,               "continuous integration": _CI_CD,
    "continuous deployment": _CI_CD, "continuous delivery": _CI_CD,
    "devops": "DevOps",          "dev ops": "DevOps",
    "sre": "SRE",                "site reliability": "SRE",
    "infrastructure as code": "Infrastructure as Code", "iac": "Infrastructure as Code",
    "linux": "Linux",            "ubuntu": "Linux",             "centos": "Linux",          "debian": "Linux",  "unix": "Linux",
    "networking": "Networking",  "tcp/ip": "Networking",        "dns": "Networking",
    "nginx": "Nginx",
    "apache": "Apache",
    "load balancing": "Load Balancing",
    "monitoring": "Monitoring",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "elk": _ELK_STACK,           "elk stack": _ELK_STACK,       "elasticsearch logstash kibana": _ELK_STACK,
    "logstash": "Logstash",
    "kibana": "Kibana",
    "splunk": "Splunk",
    "cloudwatch": "AWS CloudWatch", "aws cloudwatch": "AWS CloudWatch",
    "lambda": "AWS Lambda",      "aws lambda": "AWS Lambda",
    "serverless": "Serverless",
    "microservices": "Microservices", "micro services": "Microservices",
    "service mesh": "Service Mesh",
    "istio": "Istio",
    "kafka": "Kafka",            "apache kafka": "Kafka",
    "rabbitmq": "RabbitMQ",      "rabbit mq": "RabbitMQ",
    "celery": "Celery",
    "message queue": "Message Queue",
    "pubsub": "Pub/Sub",         "pub/sub": "Pub/Sub",

    # ── Version Control ────────────────────────────────────────────
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "mercurial": "Mercurial",
    "version control": "Git",

    # ── APIs & Integration ─────────────────────────────────────────
    "rest api": _REST_API,       "rest apis": _REST_API,        "restful api": _REST_API,
    "restful apis": _REST_API,   "restful": _REST_API,          "rest": _REST_API,
    "api": "API Development",    "api development": "API Development",
    "api design": "API Design",  "api integration": "API Integration",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "soap": "SOAP",
    "webhook": "Webhooks",       "webhooks": "Webhooks",
    "websocket": "WebSockets",   "websockets": "WebSockets",
    "oauth": "OAuth",            "oauth2": "OAuth",
    "jwt": "JWT",                "json web token": "JWT",
    "openapi": "OpenAPI",
    "swagger": "Swagger",

    # ── Machine Learning & AI ──────────────────────────────────────
    "machine learning": _MACHINE_LEARNING, "ml": _MACHINE_LEARNING,
    "deep learning": "Deep Learning",      "dl": "Deep Learning",
    "artificial intelligence": "AI",       "ai": "AI",           "ai/ml": _MACHINE_LEARNING,
    "tensorflow": "TensorFlow",            "tf": "TensorFlow",
    "pytorch": "PyTorch",                  "torch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "scikit-learn",        "scikit learn": "scikit-learn", "sklearn": "scikit-learn",
    "hugging face": "Hugging Face",        "huggingface": "Hugging Face",
    "transformers": "Transformers",
    "llm": "LLM",                          "large language model": "LLM",  "llms": "LLM",
    "langchain": "LangChain",              "lang chain": "LangChain",
    "openai": "OpenAI",                    "open ai": "OpenAI",
    "gpt": "GPT",                          "chatgpt": "GPT",
    "nlp": "NLP",                          "natural language processing": "NLP",
    "computer vision": _COMPUTER_VISION,   "cv": _COMPUTER_VISION,
    "object detection": _COMPUTER_VISION,  "image recognition": _COMPUTER_VISION,
    "neural network": _NEURAL_NETWORKS,    "neural networks": _NEURAL_NETWORKS,
    "cnn": _NEURAL_NETWORKS,               "rnn": _NEURAL_NETWORKS,        "lstm": _NEURAL_NETWORKS,
    "gan": "GANs",
    "reinforcement learning": "Reinforcement Learning", "rl": "Reinforcement Learning",
    "mlops": "MLOps",                      "ml ops": "MLOps",
    "feature engineering": "Feature Engineering",
    "model deployment": "Model Deployment",
    "model training": _MACHINE_LEARNING,
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "random forest": _MACHINE_LEARNING,
    "faiss": "FAISS",

    # ── Data Science & Analytics ───────────────────────────────────
    "data science": "Data Science",
    "data analysis": _DATA_ANALYSIS,       "data analytics": _DATA_ANALYSIS,
    "data engineering": "Data Engineering",
    "data visualization": _DATA_VIZ,       "data viz": _DATA_VIZ,
    "pandas": "Pandas",
    "numpy": "NumPy",                       "np": "NumPy",
    "matplotlib": "matplotlib",             "seaborn": "matplotlib",
    "plotly": "Plotly",
    "tableau": "Tableau",
    "power bi": "Power BI",                 "powerbi": "Power BI",
    "looker": "Looker",
    "metabase": "Metabase",
    "jupyter": _JUPYTER,                    "jupyter notebook": _JUPYTER,
    "jupyter lab": _JUPYTER,               "jupyterlab": _JUPYTER,
    "statistics": "Statistics",             "statistical analysis": "Statistics",  "statistical modeling": "Statistics",
    "excel": "Excel",                       "ms excel": "Excel",            "microsoft excel": "Excel",
    "google sheets": "Google Sheets",       "spreadsheets": "Excel",
    "etl": "ETL",
    "data pipeline": "Data Pipelines",      "data pipelines": "Data Pipelines",
    "data warehouse": "Data Warehousing",   "data warehousing": "Data Warehousing",
    "data lake": "Data Lakes",              "data lakes": "Data Lakes",
    "big data": "Big Data",
    "hadoop": "Hadoop",                     "apache hadoop": "Hadoop",
    "spark": "Spark",                       "apache spark": "Spark",        "pyspark": "Spark",
    "hive": "Hive",
    "airflow": "Airflow",                   "apache airflow": "Airflow",
    "dbt": "dbt",                           "data build tool": "dbt",
    "snowflake": "Snowflake",
    "redshift": "AWS Redshift",             "aws redshift": "AWS Redshift",
    "bigquery": "BigQuery",                 "google bigquery": "BigQuery",
    "databricks": "Databricks",
    "a/b testing": "A/B Testing",           "ab testing": "A/B Testing",

    # ── Security ───────────────────────────────────────────────────
    "cybersecurity": "Cybersecurity",       "cyber security": "Cybersecurity",
    "information security": "Cybersecurity", "infosec": "Cybersecurity",
    "network security": "Network Security",
    "application security": "Application Security", "appsec": "Application Security",
    "penetration testing": _PEN_TESTING,    "pen testing": _PEN_TESTING,
    "pentest": _PEN_TESTING,               "ethical hacking": _PEN_TESTING,
    "vulnerability assessment": "Security Testing",
    "siem": "SIEM",
    "soc": "SOC",
    "iam": "IAM",                           "identity access management": "IAM",
    "zero trust": "Zero Trust Security",
    "devsecops": "DevSecOps",              "dev sec ops": "DevSecOps",
    "ssl": _SSL_TLS,                        "tls": _SSL_TLS,                "ssl/tls": _SSL_TLS,
    "encryption": "Encryption",
    "authentication": "Authentication",     "bcrypt": "Authentication",
    "authorization": "Authorization",
    "saml": "SAML",
    "sso": "SSO",
    "firewall": "Network Security",

    # ── Mobile Development ─────────────────────────────────────────
    "react native": _REACT_NATIVE,          "react-native": _REACT_NATIVE,
    "flutter": "Flutter",
    "android": "Android",                   "android sdk": "Android",       "android development": "Android",
    "ios": "iOS",                           "ios development": "iOS",
    "swift ui": "SwiftUI",                  "swiftui": "SwiftUI",
    "xamarin": "Xamarin",
    "ionic": "Ionic",
    "expo": _REACT_NATIVE,
    "mobile development": "Mobile Development",

    # ── Testing ────────────────────────────────────────────────────
    "testing": "Testing",
    "unit testing": "Unit Testing",
    "integration testing": "Integration Testing",
    "e2e testing": "E2E Testing",           "end to end testing": "E2E Testing",
    "test driven development": "TDD",       "tdd": "TDD",
    "bdd": "BDD",                           "behavior driven development": "BDD",
    "jest": "Jest",
    "pytest": "pytest",
    "mocha": "Mocha",
    "chai": "Chai",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "postman": "Postman",
    "junit": "JUnit",
    "testng": "TestNG",
    "qa": "QA",                             "quality assurance": "QA",
    "performance testing": "Performance Testing",
    "load testing": "Load Testing",

    # ── Project Management & Agile ─────────────────────────────────
    "agile": "Agile",                       "agile methodologies": "Agile",  "agile methodology": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "jira": "Jira",
    "confluence": "Confluence",
    "trello": "Trello",
    "asana": "Asana",
    "project management": "Project Management",
    "product management": "Product Management",
    "sprint planning": "Agile",
    "stakeholder management": "Stakeholder Management",
    "team management": "Team Management",   "team leadership": "Team Management",
    "leadership": "Leadership",
    "communication": "Communication",
    "problem solving": "Problem Solving",

    # ── Big Data & Streaming ───────────────────────────────────────
    "mapreduce": "MapReduce",               "map reduce": "MapReduce",
    "hbase": "HBase",
    "pig": "Pig",
    "flink": "Apache Flink",                "apache flink": "Apache Flink",
    "storm": "Apache Storm",                "apache storm": "Apache Storm",
    "nifi": "Apache NiFi",                  "apache nifi": "Apache NiFi",

    # ── Architecture & Design ──────────────────────────────────────
    "system design": "System Design",
    "monolith": "Monolithic Architecture",
    "event driven": "Event-Driven Architecture", "event-driven": "Event-Driven Architecture",
    "domain driven design": "Domain-Driven Design", "ddd": "Domain-Driven Design",
    "design patterns": "Design Patterns",
    "solid": "SOLID Principles",            "solid principles": "SOLID Principles",
    "clean architecture": "Clean Architecture",
    "api gateway": "API Gateway",
    "load balancer": "Load Balancing",
    "caching": "Caching",
    "cdn": "CDN",
    "scalability": "Scalability",
    "high availability": "High Availability",
    "distributed systems": "Distributed Systems",

    # ── Blockchain & Web3 ──────────────────────────────────────────
    "blockchain": "Blockchain",
    "solidity": "Solidity",
    "ethereum": "Ethereum",
    "smart contracts": "Smart Contracts",
    "web3": "Web3",                         "web3.js": "Web3",
    "defi": "DeFi",
    "nft": "NFT",

    # ── Tools & IDEs ───────────────────────────────────────────────
    "windows server": "Windows Server",
    "active directory": "Active Directory",
    "ldap": "LDAP",
    "virtualbox": "Virtualization",
    "vmware": "VMware",
    "vagrant": "Vagrant",
    "makefile": "Makefile",
    "cmake": "CMake",
    "maven": "Maven",
    "gradle": "Gradle",
    "npm": "npm",
    "yarn": "Yarn",
    "pip": "pip",
    "poetry": "Poetry",
    "conda": "Conda",                       "anaconda": "Conda",
    "vscode": _VS_CODE,                     "vs code": _VS_CODE,            "visual studio code": _VS_CODE,
    "visual studio": "Visual Studio",
    "intellij": "IntelliJ IDEA",
    "pycharm": "PyCharm",
    "eclipse": "Eclipse",
    "vim": "Vim",
    "emacs": "Emacs",
    "slack": "Slack",
    "notion": "Notion",

    # ── General / Misc ─────────────────────────────────────────────
    "mern": "MERN Stack",                   "mern stack": "MERN Stack",
    "mean": "MEAN Stack",                   "mean stack": "MEAN Stack",
    "lamp": "LAMP Stack",
    "full stack": "Full Stack Development", "fullstack": "Full Stack Development",
    "backend": _BACKEND_DEV,               "back end": _BACKEND_DEV,        "back-end": _BACKEND_DEV,
    "frontend": _FRONTEND_DEV,             "front end": _FRONTEND_DEV,      "front-end": _FRONTEND_DEV,
    "algorithms": "Algorithms",
    "data structures": _DATA_STRUCTURES,   "data structures and algorithms": _DATA_STRUCTURES, "dsa": _DATA_STRUCTURES,
    "oop": "OOP",                           "object oriented programming": "OOP", "object-oriented programming": "OOP",
    "functional programming": "Functional Programming",
    "simulation": "Simulation",
    "analysis": _DATA_ANALYSIS,
    "software": "Software Development",
    "programming": "Programming",           "programming basics": "Programming",
    "dashboards": _DATA_VIZ,
    "validation": "Testing",
    "crud": _BACKEND_DEV,
}


def normalize_skill(raw: str) -> str:
    """Normalize a raw skill string into a canonical display name."""
    if not raw:
        return ""
    lower = raw.strip().lower()
    return _SKILL_NORMALIZATION_MAP.get(lower, raw.strip())