# Generated by Django 5.0.14 on 2026-04-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_recommended_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
    ]
